name: grapheme_splitter
version: 1.0.0
author: Javier Lecuona <javierlecuona@gmail.com>
description: A Dart library that breaks strings into their individual user-perceived characters.
homepage: https://github.com/javiercbk/grapheme_splitter
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:

dev_dependencies:
  test: "^1.3.0"
  path: "^1.5.1"
